A:
	g++ -std=c++11 A.cpp
B:
	g++ -std=c++11 B.cpp
C:
	g++ -std=c++11 C.cpp
D:
	g++ -std=c++11 D.cpp
E:
	g++ -std=c++11 E.cpp
F:
	g++ -std=c++11 F.cpp
G:
	g++ -std=c++11 G.cpp
H:
	g++ -std=c++11 H.cpp
I:
	g++ -std=c++11 I.cpp
J:
	g++ -std=c++11 J.cpp
K:
	g++ -std=c++11 K.cpp
L:
	g++ -std=c++11 L.cpp
